name: ${COMPOSE_PROJECT_NAME:-lakodi}

services:
  lakodi-redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data

volumes:
  lakodi_frontend_node_modules:
  lakodi_frontend_next:
