import type { AccountingNewModuleDefinition, AccountingNewModuleId } from "@/types/accountingNew";
import type { AccountingNewModuleRegistryEntry } from "@/types/accountingNewMetadata";

const ACCOUNTING_NEW_BASE_ROUTE = "/admin/ucetnictvi-new";

export const accountingNewModuleRegistry: AccountingNewModuleRegistryEntry[] = [
  {
    id: "dashboard",
    route: ACCOUNTING_NEW_BASE_ROUTE,
    labelKey: "moduleRegistry.dashboard.label",
    descriptionKey: "moduleRegistry.dashboard.description",
    entityType: "dashboard",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "dashboard",
      labelKey: "rag.entityTypes.dashboard",
      searchableFields: [
        { field: "documentsLoaded", labelKey: "rag.searchableFields.documentsLoaded", weight: 3 },
        { field: "expensesLoaded", labelKey: "rag.searchableFields.expensesLoaded", weight: 3 },
        { field: "bankTransactionsLoaded", labelKey: "rag.searchableFields.bankTransactionsLoaded", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.dashboard",
      aliasKeys: ["voice.aliases.dashboard"],
    },
    relatedModuleIds: ["documents", "expenses", "suppliers", "bank-transactions", "payment-matching"],
    gridModuleId: "dashboard",
  },
  {
    id: "documents",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#documents`,
    labelKey: "moduleRegistry.documents.label",
    descriptionKey: "moduleRegistry.documents.description",
    entityType: "document",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "document",
      labelKey: "rag.entityTypes.document",
      searchableFields: [
        { field: "invoiceNumber", labelKey: "rag.searchableFields.invoiceNumber", weight: 5 },
        { field: "variableSymbol", labelKey: "rag.searchableFields.variableSymbol", weight: 5 },
        { field: "customerName", labelKey: "rag.searchableFields.customerName", weight: 4 },
      ],
    },
    voice: {
      labelKey: "voice.labels.documents",
      aliasKeys: ["voice.aliases.documents"],
    },
    relatedModuleIds: ["document-detail", "payment-matching"],
    gridModuleId: "documents",
  },
  {
    id: "document-detail",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}/doklady/[id]`,
    labelKey: "moduleRegistry.documentDetail.label",
    descriptionKey: "moduleRegistry.documentDetail.description",
    entityType: "document",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "document",
      labelKey: "rag.entityTypes.document",
      searchableFields: [
        { field: "invoiceNumber", labelKey: "rag.searchableFields.invoiceNumber", weight: 5 },
        { field: "note", labelKey: "rag.searchableFields.note", weight: 2 },
        { field: "customerName", labelKey: "rag.searchableFields.customerName", weight: 4 },
      ],
    },
    voice: {
      labelKey: "voice.labels.documentDetail",
      aliasKeys: ["voice.aliases.documentDetail"],
    },
    relatedModuleIds: ["documents", "payment-matching"],
  },
  {
    id: "expenses",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#expenses`,
    labelKey: "moduleRegistry.expenses.label",
    descriptionKey: "moduleRegistry.expenses.description",
    entityType: "expense",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "expense",
      labelKey: "rag.entityTypes.expense",
      searchableFields: [
        { field: "expenseNumber", labelKey: "rag.searchableFields.expenseNumber", weight: 5 },
        { field: "variableSymbol", labelKey: "rag.searchableFields.variableSymbol", weight: 4 },
        { field: "supplierName", labelKey: "rag.searchableFields.supplierName", weight: 4 },
      ],
    },
    voice: {
      labelKey: "voice.labels.expenses",
      aliasKeys: ["voice.aliases.expenses"],
    },
    relatedModuleIds: ["expense-detail", "suppliers"],
    gridModuleId: "expenses",
  },
  {
    id: "expense-detail",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}/vydaje/[id]`,
    labelKey: "moduleRegistry.expenseDetail.label",
    descriptionKey: "moduleRegistry.expenseDetail.description",
    entityType: "expense",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "expense",
      labelKey: "rag.entityTypes.expense",
      searchableFields: [
        { field: "expenseNumber", labelKey: "rag.searchableFields.expenseNumber", weight: 5 },
        { field: "note", labelKey: "rag.searchableFields.note", weight: 2 },
        { field: "supplierName", labelKey: "rag.searchableFields.supplierName", weight: 4 },
      ],
    },
    voice: {
      labelKey: "voice.labels.expenseDetail",
      aliasKeys: ["voice.aliases.expenseDetail"],
    },
    relatedModuleIds: ["expenses", "suppliers"],
  },
  {
    id: "suppliers",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#suppliers`,
    labelKey: "moduleRegistry.suppliers.label",
    descriptionKey: "moduleRegistry.suppliers.description",
    entityType: "supplier",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "supplier",
      labelKey: "rag.entityTypes.supplier",
      searchableFields: [
        { field: "name", labelKey: "rag.searchableFields.supplierName", weight: 5 },
        { field: "ico", labelKey: "rag.searchableFields.ico", weight: 4 },
        { field: "dic", labelKey: "rag.searchableFields.dic", weight: 4 },
      ],
    },
    voice: {
      labelKey: "voice.labels.suppliers",
      aliasKeys: ["voice.aliases.suppliers"],
    },
    relatedModuleIds: ["supplier-detail", "expenses"],
    gridModuleId: "suppliers",
  },
  {
    id: "supplier-detail",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}/dodavatele/[id]`,
    labelKey: "moduleRegistry.supplierDetail.label",
    descriptionKey: "moduleRegistry.supplierDetail.description",
    entityType: "supplier",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "supplier",
      labelKey: "rag.entityTypes.supplier",
      searchableFields: [
        { field: "name", labelKey: "rag.searchableFields.supplierName", weight: 5 },
        { field: "note", labelKey: "rag.searchableFields.note", weight: 2 },
        { field: "country", labelKey: "rag.searchableFields.country", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.supplierDetail",
      aliasKeys: ["voice.aliases.supplierDetail"],
    },
    relatedModuleIds: ["suppliers", "expenses"],
  },
  {
    id: "bank-transactions",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#bank-transactions`,
    labelKey: "moduleRegistry.bankTransactions.label",
    descriptionKey: "moduleRegistry.bankTransactions.description",
    entityType: "bank_transaction",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "bank_transaction",
      labelKey: "rag.entityTypes.bank_transaction",
      searchableFields: [
        { field: "counterpartyName", labelKey: "rag.searchableFields.counterpartyName", weight: 5 },
        { field: "variableSymbol", labelKey: "rag.searchableFields.variableSymbol", weight: 4 },
        { field: "message", labelKey: "rag.searchableFields.message", weight: 3 },
      ],
    },
    voice: {
      labelKey: "voice.labels.bankTransactions",
      aliasKeys: ["voice.aliases.bankTransactions"],
    },
    relatedModuleIds: ["bank-transaction-detail", "payment-matching"],
    gridModuleId: "bank-transactions",
  },
  {
    id: "bank-transaction-detail",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}/bankovni-transakce/[id]`,
    labelKey: "moduleRegistry.bankTransactionDetail.label",
    descriptionKey: "moduleRegistry.bankTransactionDetail.description",
    entityType: "bank_transaction",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "bank_transaction",
      labelKey: "rag.entityTypes.bank_transaction",
      searchableFields: [
        { field: "counterpartyName", labelKey: "rag.searchableFields.counterpartyName", weight: 5 },
        { field: "message", labelKey: "rag.searchableFields.message", weight: 3 },
        { field: "status", labelKey: "rag.searchableFields.status", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.bankTransactionDetail",
      aliasKeys: ["voice.aliases.bankTransactionDetail"],
    },
    relatedModuleIds: ["bank-transactions", "payment-matching"],
  },
  {
    id: "payment-matching",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#payment-matching`,
    labelKey: "moduleRegistry.paymentMatching.label",
    descriptionKey: "moduleRegistry.paymentMatching.description",
    entityType: "payment_match",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "payment_match",
      labelKey: "rag.entityTypes.payment_match",
      searchableFields: [
        { field: "status", labelKey: "rag.searchableFields.status", weight: 4 },
        { field: "reason", labelKey: "rag.searchableFields.reason", weight: 3 },
        { field: "confidence", labelKey: "rag.searchableFields.confidence", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.paymentMatching",
      aliasKeys: ["voice.aliases.paymentMatching"],
    },
    relatedModuleIds: ["bank-transactions", "bank-transaction-detail", "documents", "expenses"],
    gridModuleId: "payment-matching",
  },
  {
    id: "reminders",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#reminders`,
    labelKey: "moduleRegistry.reminders.label",
    descriptionKey: "moduleRegistry.reminders.description",
    entityType: "todo",
    readAvailability: "placeholder",
    writeEnabled: false,
    featureStatus: "deferred",
    rag: {
      entityType: "todo",
      labelKey: "rag.entityTypes.todo",
      searchableFields: [
        { field: "title", labelKey: "rag.searchableFields.title", weight: 4 },
        { field: "message", labelKey: "rag.searchableFields.message", weight: 3 },
      ],
    },
    voice: {
      labelKey: "voice.labels.reminders",
      aliasKeys: ["voice.aliases.reminders"],
    },
    relatedModuleIds: ["dashboard"],
    gridModuleId: "reminders",
  },
  {
    id: "attachments",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#attachments`,
    labelKey: "moduleRegistry.attachments.label",
    descriptionKey: "moduleRegistry.attachments.description",
    entityType: "attachment",
    readAvailability: "placeholder",
    writeEnabled: false,
    featureStatus: "deferred",
    rag: {
      entityType: "attachment",
      labelKey: "rag.entityTypes.attachment",
      searchableFields: [
        { field: "originalFilename", labelKey: "rag.searchableFields.originalFilename", weight: 5 },
        { field: "attachmentType", labelKey: "rag.searchableFields.attachmentType", weight: 3 },
      ],
    },
    voice: {
      labelKey: "voice.labels.attachments",
      aliasKeys: ["voice.aliases.attachments"],
    },
    relatedModuleIds: ["documents", "expenses"],
    gridModuleId: "attachments",
  },
  {
    id: "recurring",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#recurring`,
    labelKey: "moduleRegistry.recurring.label",
    descriptionKey: "moduleRegistry.recurring.description",
    entityType: "recurring_template",
    readAvailability: "placeholder",
    writeEnabled: false,
    featureStatus: "deferred",
    rag: {
      entityType: "recurring_template",
      labelKey: "rag.entityTypes.recurring_template",
      searchableFields: [
        { field: "name", labelKey: "rag.searchableFields.name", weight: 4 },
        { field: "status", labelKey: "rag.searchableFields.status", weight: 3 },
      ],
    },
    voice: {
      labelKey: "voice.labels.recurring",
      aliasKeys: ["voice.aliases.recurring"],
    },
    relatedModuleIds: ["dashboard"],
    gridModuleId: "recurring",
  },
  {
    id: "exports",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#exports`,
    labelKey: "moduleRegistry.exports.label",
    descriptionKey: "moduleRegistry.exports.description",
    entityType: "audit_event",
    readAvailability: "placeholder",
    writeEnabled: false,
    featureStatus: "future",
    rag: {
      entityType: "audit_event",
      labelKey: "rag.entityTypes.audit_event",
      searchableFields: [
        { field: "entityType", labelKey: "rag.searchableFields.entityType", weight: 2 },
        { field: "message", labelKey: "rag.searchableFields.message", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.exports",
      aliasKeys: ["voice.aliases.exports"],
    },
    relatedModuleIds: ["dashboard", "audit"],
    gridModuleId: "exports",
  },
  {
    id: "audit",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#audit`,
    labelKey: "moduleRegistry.audit.label",
    descriptionKey: "moduleRegistry.audit.description",
    entityType: "audit_event",
    readAvailability: "placeholder",
    writeEnabled: false,
    featureStatus: "deferred",
    rag: {
      entityType: "audit_event",
      labelKey: "rag.entityTypes.audit_event",
      searchableFields: [
        { field: "eventType", labelKey: "rag.searchableFields.eventType", weight: 4 },
        { field: "entityType", labelKey: "rag.searchableFields.entityType", weight: 3 },
        { field: "message", labelKey: "rag.searchableFields.message", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.audit",
      aliasKeys: ["voice.aliases.audit"],
    },
    relatedModuleIds: ["dashboard"],
    gridModuleId: "audit",
  },
];

export const accountingNewGridModuleIds: AccountingNewModuleId[] = [
  "dashboard",
  "documents",
  "expenses",
  "suppliers",
  "bank-transactions",
  "payment-matching",
  "reminders",
  "attachments",
  "recurring",
  "exports",
  "audit",
];

export function mapRegistryEntryToModuleDefinition(entry: AccountingNewModuleRegistryEntry, title: string, description: string): AccountingNewModuleDefinition {
  return {
    id: entry.gridModuleId ?? "dashboard",
    title,
    description,
    availability: entry.readAvailability,
  };
}
