import type { AccountingNewModuleDefinition, AccountingNewModuleId } from "@/types/accountingNew";
import type { AccountingNewModuleRegistryEntry } from "@/types/accountingNewMetadata";

const ACCOUNTING_NEW_BASE_ROUTE = "/admin/ucetnictvi-new";

type AccountingNewModuleRegistrySeed = Omit<AccountingNewModuleRegistryEntry, "capabilities">;

function createRegistryEntry(entry: AccountingNewModuleRegistrySeed): AccountingNewModuleRegistryEntry {
  const canRead = entry.readAvailability === "read-only";

  return {
    ...entry,
    capabilities: {
      read: entry.readAvailability,
      write: entry.writeEnabled,
      canRead,
      canCreate: false,
      canUpdate: false,
      canDelete: false,
      canSend: false,
      canExport: false,
      canImport: false,
      canApply: false,
      canGenerate: false,
    },
  };
}

export const accountingNewModuleRegistry: AccountingNewModuleRegistryEntry[] = [
  createRegistryEntry({
    id: "dashboard",
    route: ACCOUNTING_NEW_BASE_ROUTE,
    labelKey: "moduleRegistry.dashboard.label",
    descriptionKey: "moduleRegistry.dashboard.description",
    entityType: "dashboard",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "dashboard",
      labelKey: "rag.entityTypes.dashboard",
      searchableFields: [
        { field: "documentsLoaded", labelKey: "rag.searchableFields.documentsLoaded", weight: 3 },
        { field: "expensesLoaded", labelKey: "rag.searchableFields.expensesLoaded", weight: 3 },
        { field: "bankTransactionsLoaded", labelKey: "rag.searchableFields.bankTransactionsLoaded", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.dashboard",
      aliasKeys: ["voice.aliases.dashboard"],
    },
    relatedModuleIds: ["documents", "expenses", "suppliers", "bank-transactions", "payment-matching"],
    gridModuleId: "dashboard",
  }),
  createRegistryEntry({
    id: "documents",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#documents`,
    labelKey: "moduleRegistry.documents.label",
    descriptionKey: "moduleRegistry.documents.description",
    entityType: "document",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "document",
      labelKey: "rag.entityTypes.document",
      searchableFields: [
        { field: "invoiceNumber", labelKey: "rag.searchableFields.invoiceNumber", weight: 5 },
        { field: "variableSymbol", labelKey: "rag.searchableFields.variableSymbol", weight: 5 },
        { field: "customerName", labelKey: "rag.searchableFields.customerName", weight: 4 },
      ],
    },
    voice: {
      labelKey: "voice.labels.documents",
      aliasKeys: ["voice.aliases.documents"],
    },
    relatedModuleIds: ["document-detail", "payment-matching"],
    gridModuleId: "documents",
  }),
  createRegistryEntry({
    id: "document-detail",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}/doklady/[id]`,
    labelKey: "moduleRegistry.documentDetail.label",
    descriptionKey: "moduleRegistry.documentDetail.description",
    entityType: "document",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "document",
      labelKey: "rag.entityTypes.document",
      searchableFields: [
        { field: "invoiceNumber", labelKey: "rag.searchableFields.invoiceNumber", weight: 5 },
        { field: "note", labelKey: "rag.searchableFields.note", weight: 2 },
        { field: "customerName", labelKey: "rag.searchableFields.customerName", weight: 4 },
      ],
    },
    voice: {
      labelKey: "voice.labels.documentDetail",
      aliasKeys: ["voice.aliases.documentDetail"],
    },
    relatedModuleIds: ["documents", "payment-matching"],
  }),
  createRegistryEntry({
    id: "expenses",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#expenses`,
    labelKey: "moduleRegistry.expenses.label",
    descriptionKey: "moduleRegistry.expenses.description",
    entityType: "expense",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "expense",
      labelKey: "rag.entityTypes.expense",
      searchableFields: [
        { field: "expenseNumber", labelKey: "rag.searchableFields.expenseNumber", weight: 5 },
        { field: "variableSymbol", labelKey: "rag.searchableFields.variableSymbol", weight: 4 },
        { field: "supplierName", labelKey: "rag.searchableFields.supplierName", weight: 4 },
      ],
    },
    voice: {
      labelKey: "voice.labels.expenses",
      aliasKeys: ["voice.aliases.expenses"],
    },
    relatedModuleIds: ["expense-detail", "suppliers"],
    gridModuleId: "expenses",
  }),
  createRegistryEntry({
    id: "expense-detail",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}/vydaje/[id]`,
    labelKey: "moduleRegistry.expenseDetail.label",
    descriptionKey: "moduleRegistry.expenseDetail.description",
    entityType: "expense",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "expense",
      labelKey: "rag.entityTypes.expense",
      searchableFields: [
        { field: "expenseNumber", labelKey: "rag.searchableFields.expenseNumber", weight: 5 },
        { field: "note", labelKey: "rag.searchableFields.note", weight: 2 },
        { field: "supplierName", labelKey: "rag.searchableFields.supplierName", weight: 4 },
      ],
    },
    voice: {
      labelKey: "voice.labels.expenseDetail",
      aliasKeys: ["voice.aliases.expenseDetail"],
    },
    relatedModuleIds: ["expenses", "suppliers"],
  }),
  createRegistryEntry({
    id: "suppliers",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#suppliers`,
    labelKey: "moduleRegistry.suppliers.label",
    descriptionKey: "moduleRegistry.suppliers.description",
    entityType: "supplier",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "supplier",
      labelKey: "rag.entityTypes.supplier",
      searchableFields: [
        { field: "name", labelKey: "rag.searchableFields.supplierName", weight: 5 },
        { field: "ico", labelKey: "rag.searchableFields.ico", weight: 4 },
        { field: "dic", labelKey: "rag.searchableFields.dic", weight: 4 },
      ],
    },
    voice: {
      labelKey: "voice.labels.suppliers",
      aliasKeys: ["voice.aliases.suppliers"],
    },
    relatedModuleIds: ["supplier-detail", "expenses"],
    gridModuleId: "suppliers",
  }),
  createRegistryEntry({
    id: "supplier-detail",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}/dodavatele/[id]`,
    labelKey: "moduleRegistry.supplierDetail.label",
    descriptionKey: "moduleRegistry.supplierDetail.description",
    entityType: "supplier",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "supplier",
      labelKey: "rag.entityTypes.supplier",
      searchableFields: [
        { field: "name", labelKey: "rag.searchableFields.supplierName", weight: 5 },
        { field: "note", labelKey: "rag.searchableFields.note", weight: 2 },
        { field: "country", labelKey: "rag.searchableFields.country", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.supplierDetail",
      aliasKeys: ["voice.aliases.supplierDetail"],
    },
    relatedModuleIds: ["suppliers", "expenses"],
  }),
  createRegistryEntry({
    id: "bank-transactions",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#bank-transactions`,
    labelKey: "moduleRegistry.bankTransactions.label",
    descriptionKey: "moduleRegistry.bankTransactions.description",
    entityType: "bank_transaction",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "bank_transaction",
      labelKey: "rag.entityTypes.bank_transaction",
      searchableFields: [
        { field: "counterpartyName", labelKey: "rag.searchableFields.counterpartyName", weight: 5 },
        { field: "variableSymbol", labelKey: "rag.searchableFields.variableSymbol", weight: 4 },
        { field: "message", labelKey: "rag.searchableFields.message", weight: 3 },
      ],
    },
    voice: {
      labelKey: "voice.labels.bankTransactions",
      aliasKeys: ["voice.aliases.bankTransactions"],
    },
    relatedModuleIds: ["bank-transaction-detail", "payment-matching"],
    gridModuleId: "bank-transactions",
  }),
  createRegistryEntry({
    id: "bank-transaction-detail",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}/bankovni-transakce/[id]`,
    labelKey: "moduleRegistry.bankTransactionDetail.label",
    descriptionKey: "moduleRegistry.bankTransactionDetail.description",
    entityType: "bank_transaction",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "bank_transaction",
      labelKey: "rag.entityTypes.bank_transaction",
      searchableFields: [
        { field: "counterpartyName", labelKey: "rag.searchableFields.counterpartyName", weight: 5 },
        { field: "message", labelKey: "rag.searchableFields.message", weight: 3 },
        { field: "status", labelKey: "rag.searchableFields.status", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.bankTransactionDetail",
      aliasKeys: ["voice.aliases.bankTransactionDetail"],
    },
    relatedModuleIds: ["bank-transactions", "payment-matching"],
  }),
  createRegistryEntry({
    id: "payment-matching",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#payment-matching`,
    labelKey: "moduleRegistry.paymentMatching.label",
    descriptionKey: "moduleRegistry.paymentMatching.description",
    entityType: "payment_match",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "payment_match",
      labelKey: "rag.entityTypes.payment_match",
      searchableFields: [
        { field: "status", labelKey: "rag.searchableFields.status", weight: 4 },
        { field: "reason", labelKey: "rag.searchableFields.reason", weight: 3 },
        { field: "confidence", labelKey: "rag.searchableFields.confidence", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.paymentMatching",
      aliasKeys: ["voice.aliases.paymentMatching"],
    },
    relatedModuleIds: ["bank-transactions", "bank-transaction-detail", "documents", "expenses"],
    gridModuleId: "payment-matching",
  }),
  createRegistryEntry({
    id: "reminders",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#reminders`,
    labelKey: "moduleRegistry.reminders.label",
    descriptionKey: "moduleRegistry.reminders.description",
    entityType: "todo",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "todo",
      labelKey: "rag.entityTypes.todo",
      searchableFields: [
        { field: "title", labelKey: "rag.searchableFields.title", weight: 5 },
        { field: "message", labelKey: "rag.searchableFields.message", weight: 4 },
        { field: "status", labelKey: "rag.searchableFields.status", weight: 3 },
        { field: "dueDate", labelKey: "rag.searchableFields.dueDate", weight: 4 },
        { field: "relatedInvoiceNumber", labelKey: "rag.searchableFields.relatedInvoiceNumber", weight: 3 },
      ],
    },
    voice: {
      labelKey: "voice.labels.reminders",
      aliasKeys: ["voice.aliases.reminders"],
    },
    relatedModuleIds: ["todo-detail", "dashboard", "documents", "expenses"],
    gridModuleId: "reminders",
  }),
  createRegistryEntry({
    id: "todo-detail",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}/ukoly/[id]`,
    labelKey: "moduleRegistry.todoDetail.label",
    descriptionKey: "moduleRegistry.todoDetail.description",
    entityType: "todo",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "todo",
      labelKey: "rag.entityTypes.todo",
      searchableFields: [
        { field: "title", labelKey: "rag.searchableFields.title", weight: 5 },
        { field: "message", labelKey: "rag.searchableFields.message", weight: 4 },
        { field: "status", labelKey: "rag.searchableFields.status", weight: 3 },
        { field: "dueDate", labelKey: "rag.searchableFields.dueDate", weight: 4 },
      ],
    },
    voice: {
      labelKey: "voice.labels.todoDetail",
      aliasKeys: ["voice.aliases.todoDetail"],
    },
    relatedModuleIds: ["reminders", "documents", "expenses"],
  }),
  createRegistryEntry({
    id: "reminder-emails",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#reminder-emails`,
    labelKey: "moduleRegistry.reminderEmails.label",
    descriptionKey: "moduleRegistry.reminderEmails.description",
    entityType: "reminder_email",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "reminder_email",
      labelKey: "rag.entityTypes.reminder_email",
      searchableFields: [
        { field: "recipientEmail", labelKey: "rag.searchableFields.recipientEmail", weight: 5 },
        { field: "subject", labelKey: "rag.searchableFields.subject", weight: 5 },
        { field: "bodyPreview", labelKey: "rag.searchableFields.bodyPreview", weight: 4 },
        { field: "status", labelKey: "rag.searchableFields.status", weight: 3 },
        { field: "relatedInvoiceNumber", labelKey: "rag.searchableFields.relatedInvoiceNumber", weight: 3 },
        { field: "sentAt", labelKey: "rag.searchableFields.sentAt", weight: 2 },
        { field: "createdAt", labelKey: "rag.searchableFields.createdAt", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.reminderEmails",
      aliasKeys: ["voice.aliases.reminderEmails"],
    },
    relatedModuleIds: ["reminder-email-detail", "reminders", "documents"],
  }),
  createRegistryEntry({
    id: "reminder-email-detail",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}/upominky-emaily/[id]`,
    labelKey: "moduleRegistry.reminderEmailDetail.label",
    descriptionKey: "moduleRegistry.reminderEmailDetail.description",
    entityType: "reminder_email",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "reminder_email",
      labelKey: "rag.entityTypes.reminder_email",
      searchableFields: [
        { field: "recipientEmail", labelKey: "rag.searchableFields.recipientEmail", weight: 5 },
        { field: "subject", labelKey: "rag.searchableFields.subject", weight: 5 },
        { field: "bodyPreview", labelKey: "rag.searchableFields.bodyPreview", weight: 4 },
        { field: "message", labelKey: "rag.searchableFields.message", weight: 4 },
        { field: "sentAt", labelKey: "rag.searchableFields.sentAt", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.reminderEmailDetail",
      aliasKeys: ["voice.aliases.reminderEmailDetail"],
    },
    relatedModuleIds: ["reminder-emails", "documents", "reminders"],
  }),
  createRegistryEntry({
    id: "attachments",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#attachments`,
    labelKey: "moduleRegistry.attachments.label",
    descriptionKey: "moduleRegistry.attachments.description",
    entityType: "attachment",
    readAvailability: "placeholder",
    writeEnabled: false,
    featureStatus: "deferred",
    rag: {
      entityType: "attachment",
      labelKey: "rag.entityTypes.attachment",
      searchableFields: [
        { field: "originalFilename", labelKey: "rag.searchableFields.originalFilename", weight: 5 },
        { field: "attachmentType", labelKey: "rag.searchableFields.attachmentType", weight: 3 },
      ],
    },
    voice: {
      labelKey: "voice.labels.attachments",
      aliasKeys: ["voice.aliases.attachments"],
    },
    relatedModuleIds: ["documents", "expenses"],
    gridModuleId: "attachments",
  }),
  createRegistryEntry({
    id: "recurring",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#recurring`,
    labelKey: "moduleRegistry.recurring.label",
    descriptionKey: "moduleRegistry.recurring.description",
    entityType: "recurring_template",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "recurring_template",
      labelKey: "rag.entityTypes.recurring_template",
      searchableFields: [
        { field: "name", labelKey: "rag.searchableFields.name", weight: 5 },
        { field: "templateNumber", labelKey: "rag.searchableFields.templateNumber", weight: 4 },
        { field: "customerName", labelKey: "rag.searchableFields.customerName", weight: 4 },
        { field: "supplierName", labelKey: "rag.searchableFields.supplierName", weight: 4 },
        { field: "amount", labelKey: "rag.searchableFields.amount", weight: 4 },
        { field: "currency", labelKey: "rag.searchableFields.currency", weight: 3 },
        { field: "frequency", labelKey: "rag.searchableFields.frequency", weight: 4 },
        { field: "interval", labelKey: "rag.searchableFields.interval", weight: 4 },
        { field: "nextRunAt", labelKey: "rag.searchableFields.nextRunAt", weight: 4 },
        { field: "lastRunAt", labelKey: "rag.searchableFields.lastRunAt", weight: 3 },
        { field: "startDate", labelKey: "rag.searchableFields.startDate", weight: 2 },
        { field: "endDate", labelKey: "rag.searchableFields.endDate", weight: 2 },
        { field: "status", labelKey: "rag.searchableFields.status", weight: 4 },
        { field: "documentType", labelKey: "rag.searchableFields.documentType", weight: 3 },
        { field: "note", labelKey: "rag.searchableFields.note", weight: 2 },
        { field: "createdAt", labelKey: "rag.searchableFields.createdAt", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.recurring",
      aliasKeys: [
        "voice.aliases.recurring",
        "voice.aliases.recurringTemplate",
        "voice.aliases.recurringInvoice",
        "voice.aliases.recurringExpense",
        "voice.aliases.repeatInvoice",
        "voice.aliases.scheduledInvoice",
        "voice.aliases.scheduledExpense",
      ],
    },
    relatedModuleIds: ["recurring-detail", "dashboard", "documents", "expenses", "suppliers"],
    gridModuleId: "recurring",
  }),
  createRegistryEntry({
    id: "recurring-detail",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}/opakovane/[id]`,
    labelKey: "moduleRegistry.recurringDetail.label",
    descriptionKey: "moduleRegistry.recurringDetail.description",
    entityType: "recurring_template",
    readAvailability: "read-only",
    writeEnabled: false,
    featureStatus: "implemented-read-only",
    rag: {
      entityType: "recurring_generation",
      labelKey: "rag.entityTypes.recurring_generation",
      searchableFields: [
        { field: "name", labelKey: "rag.searchableFields.name", weight: 5 },
        { field: "templateNumber", labelKey: "rag.searchableFields.templateNumber", weight: 4 },
        { field: "status", labelKey: "rag.searchableFields.status", weight: 4 },
        { field: "runDate", labelKey: "rag.searchableFields.runDate", weight: 4 },
        { field: "nextRunAt", labelKey: "rag.searchableFields.nextRunAt", weight: 3 },
        { field: "lastRunAt", labelKey: "rag.searchableFields.lastRunAt", weight: 3 },
        { field: "message", labelKey: "rag.searchableFields.message", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.recurringDetail",
      aliasKeys: [
        "voice.aliases.recurringDetail",
        "voice.aliases.recurringTemplate",
        "voice.aliases.recurringInvoice",
        "voice.aliases.recurringExpense",
      ],
    },
    relatedModuleIds: ["recurring", "documents", "expenses", "suppliers"],
  }),
  createRegistryEntry({
    id: "exports",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#exports`,
    labelKey: "moduleRegistry.exports.label",
    descriptionKey: "moduleRegistry.exports.description",
    entityType: "export",
    readAvailability: "placeholder",
    writeEnabled: false,
    featureStatus: "future",
    rag: {
      entityType: "export",
      labelKey: "rag.entityTypes.export",
      searchableFields: [
        { field: "entityType", labelKey: "rag.searchableFields.entityType", weight: 2 },
        { field: "message", labelKey: "rag.searchableFields.message", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.exports",
      aliasKeys: ["voice.aliases.exports"],
    },
    relatedModuleIds: ["dashboard", "audit"],
    gridModuleId: "exports",
  }),
  createRegistryEntry({
    id: "audit",
    route: `${ACCOUNTING_NEW_BASE_ROUTE}#audit`,
    labelKey: "moduleRegistry.audit.label",
    descriptionKey: "moduleRegistry.audit.description",
    entityType: "audit_event",
    readAvailability: "placeholder",
    writeEnabled: false,
    featureStatus: "deferred",
    rag: {
      entityType: "audit_event",
      labelKey: "rag.entityTypes.audit_event",
      searchableFields: [
        { field: "eventType", labelKey: "rag.searchableFields.eventType", weight: 4 },
        { field: "entityType", labelKey: "rag.searchableFields.entityType", weight: 3 },
        { field: "message", labelKey: "rag.searchableFields.message", weight: 2 },
      ],
    },
    voice: {
      labelKey: "voice.labels.audit",
      aliasKeys: ["voice.aliases.audit"],
    },
    relatedModuleIds: ["dashboard"],
    gridModuleId: "audit",
  }),
];

export const accountingNewGridModuleIds: AccountingNewModuleId[] = [
  "dashboard",
  "documents",
  "expenses",
  "suppliers",
  "bank-transactions",
  "payment-matching",
  "reminders",
  "attachments",
  "recurring",
  "exports",
  "audit",
];

export function mapRegistryEntryToModuleDefinition(entry: AccountingNewModuleRegistryEntry, title: string, description: string): AccountingNewModuleDefinition {
  return {
    id: entry.gridModuleId ?? "dashboard",
    title,
    description,
    availability: entry.capabilities.read,
  };
}
